# Generated by Django 6.1.1 on 2026-09-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "region_code",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("region_name", models.CharField(max_length=50)),
                ("lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("lng", models.DecimalField(decimal_places=6, max_digits=9)),
                ("grid_nx", models.IntegerField()),
                ("grid_ny", models.IntegerField()),
            ],
        ),
    ]
