# Generated by Django 6.1.1 on 2026-10-05 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FortuneProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField()),
                ('duration_days', models.PositiveSmallIntegerField(choices=[(1, '1일'), (7, '7일'), (14, '14일'), (21, '21일')])),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FortuneProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_type', models.CharField(choices=[('SOLAR', '양력'), ('LUNAR_NORMAL', '음력 평달'), ('LUNAR_LEAP', '음력 윤달')], max_length=20)),
                ('birth_date', models.DateField()),
                ('converted_solar_date', models.DateField(blank=True, null=True)),
                ('birth_time', models.TimeField(blank=True, null=True)),
                ('birth_time_unknown', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fortune_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('birth_time__isnull', True), ('birth_time_unknown', True)), models.Q(('birth_time__isnull', False), ('birth_time_unknown', False)), _connector='OR'), name='valid_fortune_birth_time')],
            },
        ),
        migrations.CreateModel(
            name='FortunePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=100)),
                ('duration_days', models.PositiveSmallIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('calendar_type', models.CharField(choices=[('SOLAR', '양력'), ('LUNAR_NORMAL', '음력 평달'), ('LUNAR_LEAP', '음력 윤달')], max_length=20)),
                ('birth_date', models.DateField()),
                ('converted_solar_date', models.DateField()),
                ('birth_time', models.TimeField(blank=True, null=True)),
                ('birth_time_unknown', models.BooleanField(default=False)),
                ('payment_status', models.CharField(choices=[('PENDING', '결제 대기'), ('PAID', '결제 완료'), ('FAILED', '결제 실패'), ('CANCELED', '결제 취소'), ('REFUNDED', '환불')], default='PENDING', max_length=20)),
                ('payment_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('active_from', models.DateField(blank=True, null=True)),
                ('active_until', models.DateField(blank=True, null=True)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='fortune.fortuneproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fortune_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'payment_status', 'active_until'], name='fortune_active_purchase_idx')],
            },
        ),
        migrations.CreateModel(
            name='FortuneResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('lucky_color', models.CharField(max_length=50)),
                ('lucky_item', models.CharField(max_length=100)),
                ('lucky_place', models.CharField(max_length=100)),
                ('detail_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fortune_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['target_date'],
                'indexes': [models.Index(fields=['user', 'target_date'], name='fortune_user_result_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'target_date'), name='unique_fortune_result_per_user_date')],
            },
        ),
    ]
