# Generated by Django 6.1.1 on 2026-10-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="character_type",
        ),
        migrations.AddField(
            model_name="socialaccount",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="location_mode",
            field=models.CharField(
                blank=True,
                choices=[("GPS", "현재 위치"), ("MANUAL", "직접 설정")],
                max_length=10,
                null=True,
            ),
        ),
    ]
