# Generated by Django 6.1.1 on 2026-10-08 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('purpose', models.CharField(choices=[('ACADEMY', '학원'), ('COMMUTE', '출근'), ('SCHOOL', '등교'), ('PART_TIME', '알바'), ('EXERCISE', '운동'), ('CUSTOM', '직접 입력')], default='CUSTOM', max_length=20)),
                ('weekdays', models.JSONField(default=list)),
                ('outing_time', models.TimeField()),
                ('lead_minutes', models.PositiveSmallIntegerField(choices=[(10, '10분 전'), (30, '30분 전'), (60, '1시간 전'), (120, '2시간 전')], default=120)),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_schedules', to='core.region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['outing_time', 'pk'],
                'indexes': [models.Index(fields=['user', 'is_enabled'], name='situations__user_id_9be357_idx')],
            },
        ),
    ]
