# Generated by Django 6.1.1 on 2026-10-08 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('OUTING_WEATHER', '외출 날씨'), ('EXERCISE', '운동'), ('LAUNDRY', '빨래'), ('FORTUNE', '운세')], max_length=30)),
                ('target_date', models.DateField()),
                ('dedupe_key', models.CharField(max_length=150, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', '발송 대기'), ('SENT', '발송 완료'), ('FAILED', '발송 실패'), ('SKIPPED', '발송 제외')], default='PENDING', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='situations.notificationschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'notification_type', 'target_date'], name='situations__user_id_f85249_idx'), models.Index(fields=['status', 'created_at'], name='situations__status_0e6087_idx')],
            },
        ),
    ]
