# Generated by Django 6.1.1 on 2026-10-09 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('situations', '0002_notificationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drank_at', models.DateTimeField()),
                ('amount_ml', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_intakes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['drank_at', 'pk'],
                'indexes': [models.Index(fields=['user', 'drank_at'], name='situations__user_id_0835c3_idx')],
            },
        ),
    ]
