"""
Django settings for configs project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

import environ

env = environ.Env(
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, []),
)


# 로컬 개발에서는 .env.dev를 우선 사용합니다.
# 배포 서버에 .env.dev가 없으면 .env.prod를 사용합니다.
if (BASE_DIR / ".env.dev").exists():
    environ.Env.read_env(BASE_DIR / ".env.dev")
elif (BASE_DIR / ".env.prod").exists():
    environ.Env.read_env(BASE_DIR / ".env.prod")

# 프론트엔드 알림 클릭 시 이동할 기본 주소
FRONTEND_BASE_URL = env(
    "FRONTEND_BASE_URL",
    default="https://weether.kr",
)

# 스케줄러를 5분마다 실행할 예정이므로 발송 허용 구간도 5분으로 설정합니다.
WEATHER_NOTIFICATION_WINDOW_MINUTES = env.int(
    "WEATHER_NOTIFICATION_WINDOW_MINUTES",
    default=5,
)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')
KMA_SERVICE_KEY = env("KMA_SERVICE_KEY", default="")

KMA_BASE_URL = env(
    "KMA_BASE_URL",
    default="https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0",
)


ONESIGNAL_APP_ID = env("ONESIGNAL_APP_ID", default="")
ONESIGNAL_REST_API_KEY = env("ONESIGNAL_REST_API_KEY", default="")
ONESIGNAL_API_URL = env(
    "ONESIGNAL_API_URL",
    default="https://api.onesignal.com/notifications",
)
ONESIGNAL_DRY_RUN = env.bool("ONESIGNAL_DRY_RUN", default=True)


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')

# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': env.db(default="sqlite:///db.sqlite3")
}
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "accounts",
    "home",
    "situations",
    "premium",
    "community",
    "fortune",
    "mypage",
    "ads",
    "core",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=14),
    # User의 PK 필드명이 id가 아니라 user_id라면 아래 주석 해제
    # "USER_ID_FIELD": "user_id",
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "configs.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "configs.wsgi.application"

# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

AUTH_USER_MODEL = 'accounts.User'

LANGUAGE_CODE = "ko-kr"

TIME_ZONE = "Asia/Seoul"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# 사용자 성향별 알림 발송 시간
LAUNDRY_NOTIFICATION_HOUR = env.int(
    "LAUNDRY_NOTIFICATION_HOUR",
    default=7,
)
EXERCISE_MORNING_NOTIFICATION_HOUR = env.int(
    "EXERCISE_MORNING_NOTIFICATION_HOUR",
    default=6,
)
EXERCISE_EVENING_NOTIFICATION_HOUR = env.int(
    "EXERCISE_EVENING_NOTIFICATION_HOUR",
    default=17,
)
EXERCISE_GOOD_WEATHER_NOTIFICATION_HOUR = env.int(
    "EXERCISE_GOOD_WEATHER_NOTIFICATION_HOUR",
    default=9,
)
