# Generated by Django 6.1.1 on 2026-10-08 03:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cold_sensitivity', models.CharField(choices=[('VERY_SENSITIVE', '추위를 많이 타요'), ('NORMAL', '보통이에요'), ('HEAT_SENSITIVE', '더위를 더 잘 느껴요'), ('UNKNOWN', '잘 모르겠어요')], default='UNKNOWN', max_length=30)),
                ('exercise_preference', models.CharField(choices=[('MORNING', '아침에 자주 해요'), ('EVENING', '저녁에 자주 해요'), ('GOOD_WEATHER_ONLY', '날씨가 좋을 때만 해요'), ('NO_NOTIFICATION', '운동 알림은 필요 없어요')], default='NO_NOTIFICATION', max_length=30)),
                ('laundry_rain_alert', models.BooleanField(default=False)),
                ('laundry_humidity_alert', models.BooleanField(default=False)),
                ('laundry_indoor_tip', models.BooleanField(default=False)),
                ('survey_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
